services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://neondb_owner:npg_WlAG2Y6hDMfd@ep-super-sun-a5dg683i-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
      JWT_SECRET: 00ea1da4192a2030f9ae023de3b3143ed647bbab
      JWT_EXPIRE: 1h
      PORT: 3003
    volumes:
      - postgres_data:/app/prisma
volumes:
  postgres_data:

networks:
  app-network:
    external: true